### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by NintendoPSproG2** [jigsaw-4277821/PE-0.5.2h-Android#10]
### Describe your problem here.

When I try running the build, it showed that I needed AndroidTools, which I found on internet and downloaded with git, but now it shows me this. I need help!
![Captura de pantalla (20)](https://user-images.githubusercontent.com/101809971/158812285-d0202ef2-47c2-47b7-b61f-af5958a379c2.png)
 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by NintendoPSproG2** [comment]
Ok that helped, but now its stuck on this scree
![Captura de pantalla (22)](https://user-images.githubusercontent.com/101809971/158874540-6e478318-9bee-4e1f-ba9d-20ae575f195e.png)
n

**Comment by Randomxdp** [comment]
> Ok that helped, but now its stuck on this scree ![Captura de pantalla (22)](https://user-images.githubusercontent.com/101809971/158874540-6e478318-9bee-4e1f-ba9d-20ae575f195e.png) n

Download ndk r15c, it should fix the issue (i dno why but on github actions r23b works fine lol)

**Comment by NintendoPSproG2** [comment]
I spoke too fast, sorry! Also sorry I'm being so annoying on this, i kinda wanna port my mod to android. This happends now
![Captura de pantalla (23)](https://user-images.githubusercontent.com/101809971/158890080-70677fcd-872e-44be-87be-c976c93daee9.png)
.

**Comment by jigsaw-4277821** [comment]
You have to use my linc_luajit
