### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Randomxdp** [jigsaw-4277821/PE-0.5.2h-Android#11]
### Describe your bug here.

Like i said before your port crashes with lua, i just want you to fix this
Here is the video link (since in github it shows blank i dno why) 

https://streamable.com/k5c6z5

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I didnt even do anything, i just downloaded your port from actions and that happened

**Comment by Randomxdp** [comment]
So.. this is a issue with no fix..... its fine :(

**Comment by ImaginationSuperHero528** [comment]
Try lowering fps to 60

**Comment by Randomxdp** [comment]
Its at 60 fps.
