### ISSUE TITLE
How to use shaders wavy bg

### ISSUE THREAD

**Issue by sebitamontana** [jigsaw-4277821/PE-0.5.2h-Android#2]
### Describe your problem here.

How to use wavy bg shader

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by Leonard4446** [comment]
I don't like it when engines and mods come out for so long android

**Comment by lalkalolich** [comment]
> ### Describe your problem here.
> How to use wavy bg shader
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Neko, HashLink, or other build system
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

you can't make shaders for now. Shadow Mario just left that folder. It doesn't work even on pc

**Comment by sebitamontana** [comment]
:(
