### ISSUE TITLE
Cutscenes Don't Work

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [jigsaw-4277821/PE-0.5.2h-Android#23]
### Describe your bug here.

Video cutscenes just won't work like they never start!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No base download

**Comment by jigsaw-4277821** [comment]
You have to use html

**Comment by jigsaw-4277821** [comment]
You can't use only the MP4 file

**Comment by ImaginationSuperHero528** [comment]
> You can't use only the MP4 file

Why tho?! Psych doesn't support html?!

**Comment by ImaginationSuperHero528** [comment]
> You can't use only the MP4 file

Why tho?! Psych doesn't support html?!

**Comment by jigsaw-4277821** [comment]
Dumbass in my port, on android, you have to use html

**Comment by ImaginationSuperHero528** [comment]
> Dumbass in my port, on android, you have to use html

But android can run mp4?!
