### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by pasta870** [jigsaw-4277821/PE-0.5.2h-Android#3]
### Describe your bug here.

IT WONT LOAD!!!! AND IT SOFTLOCKS YOU!!!!

### Command Prompt/Terminal logs (if existing)

```bash
A
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jigsaw-4277821** [comment]
Dumbass you need a html
