### ISSUE TITLE
file path change

### ISSUE THREAD

**Issue by 0-skid** [jigsaw-4277821/PE-0.5.2h-Android#4]
### What feature do you want to get added on the **base** engine?

it doesn't make sense to have the file path hidden, so maybe just remove the . at the beginning

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by jigsaw-4277821** [comment]
I guess you want all the pngs in your gallery didn't you

**Comment by jigsaw-4277821** [comment]
I will keep it hided

**Comment by 0-skid** [comment]
> I guess you want all the pngs in your gallery didn't you

ah, that makes sense
